/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFPrincipal.java
 *
 * Created on 28/11/2011, 18:36:35
 */
package br.eventos.servicos.views;

import br.eventos.dominio.Banda;
import br.eventos.dominio.LocalDeEvento;
import br.eventos.hibernate.HibernateUtil;
import br.eventos.servicos.BandaService;
import br.eventos.servicos.LocalDeEventoService;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author tony
 */
public class JFPrincipal extends javax.swing.JFrame {

    /** Creates new form JFPrincipal */
    public JFPrincipal() {
        Session sessao = HibernateUtil.getSessionFactory().openSession();
        HibernateUtil.setSessao(sessao);
        initComponents();
        
        JLBandas.setListData(BandaService.getInstance().listarTodas().toArray());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        JTPPrincipal = new javax.swing.JTabbedPane();
        JPBandas = new javax.swing.JPanel();
        JPNovaBanda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFBandaNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFDataFormacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABandaDescricao = new javax.swing.JTextArea();
        BTNSalvarBanda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TFBandaID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JLBandas = new javax.swing.JList();
        JBBandaEditar = new javax.swing.JButton();
        JBBandaExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TFCadLocalId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFCadLocalNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFCadLocalEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TFCadLocalCapacidade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPBandas.setVisible(false);

        JPNovaBanda.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel1.setText("Nome");

        TFBandaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBandaNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de formação");

        jLabel3.setText("Descrição");

        TABandaDescricao.setColumns(20);
        TABandaDescricao.setRows(5);
        jScrollPane3.setViewportView(TABandaDescricao);

        BTNSalvarBanda.setText("Salvar");
        BTNSalvarBanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalvarBandaActionPerformed(evt);
            }
        });

        jLabel4.setText("#");

        TFBandaID.setEditable(false);
        TFBandaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBandaIDActionPerformed(evt);
            }
        });

        jButton1.setText("Limpar (sem salvar)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNovaBandaLayout = new javax.swing.GroupLayout(JPNovaBanda);
        JPNovaBanda.setLayout(JPNovaBandaLayout);
        JPNovaBandaLayout.setHorizontalGroup(
            JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNovaBandaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNovaBandaLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNSalvarBanda))
                    .addGroup(JPNovaBandaLayout.createSequentialGroup()
                        .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(TFDataFormacao, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(TFBandaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(TFBandaID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))))
                .addContainerGap())
        );
        JPNovaBandaLayout.setVerticalGroup(
            JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNovaBandaLayout.createSequentialGroup()
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBandaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBandaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFDataFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPNovaBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSalvarBanda)
                    .addComponent(jButton1)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandas"));

        JLBandas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(JLBandas);

        JBBandaEditar.setText("Editar");
        JBBandaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBandaEditarActionPerformed(evt);
            }
        });

        JBBandaExcluir.setText("Excluir");
        JBBandaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBandaExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBBandaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBBandaExcluir))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBBandaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBBandaExcluir))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPBandasLayout = new javax.swing.GroupLayout(JPBandas);
        JPBandas.setLayout(JPBandasLayout);
        JPBandasLayout.setHorizontalGroup(
            JPBandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNovaBanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPBandasLayout.setVerticalGroup(
            JPBandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBandasLayout.createSequentialGroup()
                .addComponent(JPNovaBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTPPrincipal.addTab("Bandas", JPBandas);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        JTPPrincipal.addTab("Eventos", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel5.setText("#");

        TFCadLocalId.setEditable(false);
        TFCadLocalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCadLocalIdActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome");

        TFCadLocalNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCadLocalNomeActionPerformed(evt);
            }
        });

        jLabel7.setText("Endereço");

        jLabel8.setText("Capacidade");

        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TFCadLocalId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE))
                    .addComponent(TFCadLocalNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(TFCadLocalCapacidade, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(TFCadLocalEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFCadLocalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFCadLocalNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFCadLocalEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFCadLocalCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Locais de evento"));

        jScrollPane4.setViewportView(jList2);

        jButton4.setText("Editar");

        jButton5.setText("Excluir");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTPPrincipal.addTab("Locais de Evento", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTPPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTPPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TFBandaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBandaIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TFBandaIDActionPerformed

private void BTNSalvarBandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalvarBandaActionPerformed
    Banda banda;
    BandaService servico = BandaService.getInstance();
    if(TFBandaID.getText().isEmpty()){
        banda = new Banda();
    } else {
        banda = servico.carregar(Long.parseLong(TFBandaID.getText()));
    }
    banda.setNome(TFBandaNome.getText());
    banda.setDescricao(TABandaDescricao.getText());
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    String dataDoCampo = TFDataFormacao.getText();
    try{
        Date dataformatada = format.parse(dataDoCampo);
        banda.setData(dataformatada);
        servico.persistir(banda);
        TFBandaID.setText("");
        TFBandaNome.setText("");
        TABandaDescricao.setText("");
        TFDataFormacao.setText("");
        JLBandas.setListData(servico.listarTodas().toArray());
    } catch(Exception e){
        JOptionPane.showMessageDialog(
            null
            , "Ooops... informe uma data válida dd/mm/yyyy."
        );
    }
    
    
}//GEN-LAST:event_BTNSalvarBandaActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    LocalDeEvento localEvento = new LocalDeEvento();
    LocalDeEventoService servico = LocalDeEventoService.getInstance();
    
    localEvento.setNome(TFCadLocalNome.getText());
    localEvento.setEndereco(TFCadLocalEndereco.getText());
    localEvento.setCapacidadeMaxima(Integer.parseInt(TFCadLocalCapacidade.getText()));
    if (TFCadLocalId.getText().isEmpty()){
        servico.inserir(localEvento);   
    }else{
        localEvento.setId(Long.parseLong(TFCadLocalId.getText()));
        servico.alterar(localEvento);
    }
        TFCadLocalNome.setText("");
        TFCadLocalEndereco.setText("");
        TFCadLocalCapacidade.setText("");
        TFCadLocalId.setText("");
        jList2.setListData(servico.listarTodas().toArray());
  
}//GEN-LAST:event_jButton3ActionPerformed

private void TFCadLocalNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCadLocalNomeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TFCadLocalNomeActionPerformed

private void TFCadLocalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCadLocalIdActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TFCadLocalIdActionPerformed

private void JBBandaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBandaEditarActionPerformed
    Banda bandaSelecionada = (Banda)JLBandas.getSelectedValue();
    if(bandaSelecionada != null){
        TFBandaID.setText(Long.toString(bandaSelecionada.getId()));
        TFBandaNome.setText(bandaSelecionada.getNome());
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        TFDataFormacao.setText(dataFormatada.format(bandaSelecionada.getData()));
        TABandaDescricao.setText(bandaSelecionada.getDescricao());
    } else {
        JOptionPane.showMessageDialog(
            null
            , "Ooops... você esqueceu de selecionar uma banda."
        );
    }
}//GEN-LAST:event_JBBandaEditarActionPerformed

private void TFBandaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBandaNomeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_TFBandaNomeActionPerformed

private void JBBandaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBandaExcluirActionPerformed
    Banda banda = (Banda)JLBandas.getSelectedValue();
    if(banda != null){
        int result = JOptionPane.showConfirmDialog(
            null
            , "Tem certeza que deseja excluir a banda " + banda.getNome() + "?"
            , "Atenção!"
            , JOptionPane.YES_NO_OPTION
        );
        if(result == 0){
            BandaService servico = BandaService.getInstance();
            String id = (TFBandaID.getText().isEmpty()) ? "0" : TFBandaID.getText();
            if(banda.getId() == Long.parseLong(id)){
                //limpa tudo
                TFBandaID.setText("");
                TFBandaNome.setText("");
                TABandaDescricao.setText("");
                TFDataFormacao.setText("");
            }
            servico.excluir(banda);
            JLBandas.setListData(servico.listarTodas().toArray());
        }
    } else {
        JOptionPane.showMessageDialog(
            null
            , "Ooops... você esqueceu de selecionar uma banda."
        );
    }
}//GEN-LAST:event_JBBandaExcluirActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    TFBandaID.setText("");
    TFBandaNome.setText("");
    TFDataFormacao.setText("");
    TABandaDescricao.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSalvarBanda;
    private javax.swing.JButton JBBandaEditar;
    private javax.swing.JButton JBBandaExcluir;
    private javax.swing.JList JLBandas;
    private javax.swing.JPanel JPBandas;
    private javax.swing.JPanel JPNovaBanda;
    private javax.swing.JTabbedPane JTPPrincipal;
    private javax.swing.JTextArea TABandaDescricao;
    private javax.swing.JTextField TFBandaID;
    private javax.swing.JTextField TFBandaNome;
    private javax.swing.JTextField TFCadLocalCapacidade;
    private javax.swing.JTextField TFCadLocalEndereco;
    private javax.swing.JTextField TFCadLocalId;
    private javax.swing.JTextField TFCadLocalNome;
    private javax.swing.JTextField TFDataFormacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
